# Assignment No - 5

In [1]:
import pandas as pd
import numpy as np

In [2]:
#1. Create a Series of 5 student names.
arr=np.array(['Ash','John','Alex','Perry','Lily'])
ser=pd.Series(arr)
ser

0      Ash
1     John
2     Alex
3    Perry
4     Lily
dtype: object

In [3]:
#2. Create a Series of 5 marks and display it.
ser=pd.Series([65,86,95,75,58])
ser

0    65
1    86
2    95
3    75
4    58
dtype: int64

In [4]:
#3. Create a Series with custom index labels like A, B, C, D.
ser = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])
ser

A    10
B    20
C    30
D    40
dtype: int64

In [5]:
#4. Access the third value from a Series.
ser.iloc[2]

np.int64(30)

In [6]:
#5. Access a value from a Series using its custom label.
ser['C']

np.int64(30)

In [7]:
#6. Change one value in a Series.
ser['A']=100
ser

A    100
B     20
C     30
D     40
dtype: int64

In [8]:
#7. Add 10 to every value in a numeric Series.
ser=ser+10
ser

A    110
B     30
C     40
D     50
dtype: int64

In [9]:
#8. Find the maximum value in a Series.
ser.max()

np.int64(110)

In [10]:
#9. Find the minimum value in a Series.
ser.min()

np.int64(30)

In [11]:
#10. Find the mean of a numeric Series.
ser.mean()

np.float64(57.5)

In [12]:
#11. Filter only values greater than 50 in a Series.
ser[ser>50]

A    110
dtype: int64

In [13]:
#12. Create a Series from a dictionary.
data = {'X': 1, 'Y': 2, 'Z': 3}
ser1 = pd.Series(data)
ser1

X    1
Y    2
Z    3
dtype: int64

In [14]:
#13. Check the index of a Series.
ser.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [15]:
#14. Check the values of a Series.
ser.values

array([110,  30,  40,  50])

In [16]:
#15. Convert a Series into a list.
ser.to_list()

[110, 30, 40, 50]

In [17]:
#16. Check which values in a Series are null.
ser.isna()

A    False
B    False
C    False
D    False
dtype: bool

In [18]:
#17. Fill missing values in a Series with 0.
ser.fillna(0)

A    110
B     30
C     40
D     50
dtype: int64

In [19]:
#18. Count how many times each value appears in a Series.
ser.value_counts()

110    1
30     1
40     1
50     1
Name: count, dtype: int64

In [20]:
#19. Sort a Series by values.
ser.sort_values()

B     30
C     40
D     50
A    110
dtype: int64

In [21]:
#20. Sort a Series by index.
ser.sort_index()

A    110
B     30
C     40
D     50
dtype: int64

In [22]:
#21. Create a DataFrame of 5 students with columns Name, Age, Marks.
df = pd.DataFrame({
    'Name': ['Ash', 'John', 'Alex', 'Perry', 'Lily'],
    'Age': [20, 21, 19, 22, 20],
    'Marks': [85, 38, 92, 70, 45]
})
df

    Name  Age  Marks
0    Ash   20     85
1   John   21     38
2   Alex   19     92
3  Perry   22     70
4   Lily   20     45

In [23]:
#22. Display the first 3 rows of a DataFrame.
df.head(3)

   Name  Age  Marks
0   Ash   20     85
1  John   21     38
2  Alex   19     92

In [24]:
#23. Display the last 2 rows of a DataFrame.
df.tail(2)

    Name  Age  Marks
3  Perry   22     70
4   Lily   20     45

In [25]:
#24. Display only one column from a DataFrame.
df['Age']

0    20
1    21
2    19
3    22
4    20
Name: Age, dtype: int64

In [26]:
#25. Display two columns from a DataFrame.
df[['Name', 'Age']]

    Name  Age
0    Ash   20
1   John   21
2   Alex   19
3  Perry   22
4   Lily   20

In [27]:
#26. Add a new column called Passed based on Marks > 40.
df['Passed']=df['Marks']>40
df

    Name  Age  Marks  Passed
0    Ash   20     85    True
1   John   21     38   False
2   Alex   19     92    True
3  Perry   22     70    True
4   Lily   20     45    True

In [28]:
#27. Add a new column called Bonus with fixed value 5.
df['Bonus']=5
df

    Name  Age  Marks  Passed  Bonus
0    Ash   20     85    True      5
1   John   21     38   False      5
2   Alex   19     92    True      5
3  Perry   22     70    True      5
4   Lily   20     45    True      5

In [29]:
#28. Change the values of one existing column.
df['Age'] = df['Age'] + 1
df

    Name  Age  Marks  Passed  Bonus
0    Ash   21     85    True      5
1   John   22     38   False      5
2   Alex   20     92    True      5
3  Perry   23     70    True      5
4   Lily   21     45    True      5

In [30]:
#29. Delete one column from a DataFrame.
df = df.drop(columns=['Bonus'])
df

    Name  Age  Marks  Passed
0    Ash   21     85    True
1   John   22     38   False
2   Alex   20     92    True
3  Perry   23     70    True
4   Lily   21     45    True

In [31]:
#30. Rename a column in a DataFrame.
df = df.rename(columns={'Marks': 'Score'})
df

    Name  Age  Score  Passed
0    Ash   21     85    True
1   John   22     38   False
2   Alex   20     92    True
3  Perry   23     70    True
4   Lily   21     45    True

In [32]:
#31. Set Name as index of the DataFrame.
df = df.set_index('Name')
df

       Age  Score  Passed
Name
Ash     21     85    True
John    22     38   False
Alex    20     92    True
Perry   23     70    True
Lily    21     45    True

In [33]:
#32. Reset the index back to default integers.
df = df.reset_index()

In [34]:
#33. Select the first row using iloc.
df.iloc[0]

Name       Ash
Age         21
Score       85
Passed    True
Name: 0, dtype: object

In [35]:
#34. Select a row using loc with label index.
df.loc[0]

Name       Ash
Age         21
Score       85
Passed    True
Name: 0, dtype: object

In [36]:
#35. Filter students with Marks greater than 60.
df1=df[df['Score'] > 60]
df1

    Name  Age  Score  Passed
0    Ash   21     85    True
2   Alex   20     92    True
3  Perry   23     70    True

In [37]:
#36. Filter students whose Age is less than 20.
df1=df[df['Age'] < 20]

In [38]:
#37. Find the average Marks of all students.
df['Score'].mean()

np.float64(66.0)

In [39]:
#38. Find the student with highest Marks.
df[df['Score'] == df['Score'].max()]

   Name  Age  Score  Passed
2  Alex   20     92    True

In [40]:
#39. Sort the DataFrame by Marks in ascending order.
df.sort_values(by='Score')

    Name  Age  Score  Passed
1   John   22     38   False
4   Lily   21     45    True
3  Perry   23     70    True
0    Ash   21     85    True
2   Alex   20     92    True

In [41]:
#40. Sort the DataFrame by Age in descending order.
df.sort_values(by='Age', ascending=False)

    Name  Age  Score  Passed
3  Perry   23     70    True
1   John   22     38   False
0    Ash   21     85    True
4   Lily   21     45    True
2   Alex   20     92    True

In [42]:
#41. Check DataFrame shape.
df.shape

(5, 4)

In [43]:
#42. Check DataFrame column names.
df.columns

Index(['Name', 'Age', 'Score', 'Passed'], dtype='object')

In [44]:
#43. Check DataFrame data types.
df.dtypes

Name      object
Age        int64
Score      int64
Passed      bool
dtype: object

In [45]:
#44. Check if any values are missing in the DataFrame.
df.isna().sum()

Name      0
Age       0
Score     0
Passed    0
dtype: int64

In [46]:
#45. Fill missing values in Marks with the column mean.
df['Score'] = df['Score'].fillna(df['Score'].mean())

In [47]:
#46. Drop rows containing missing values.
df.dropna()

    Name  Age  Score  Passed
0    Ash   21     85    True
1   John   22     38   False
2   Alex   20     92    True
3  Perry   23     70    True
4   Lily   21     45    True

In [48]:
#47. Count unique values in a column.
df['Name'].nunique()

5

In [49]:
#48. Find value counts of a categorical column like Department.
df['Name'].value_counts()

Name
Ash      1
John     1
Alex     1
Perry    1
Lily     1
Name: count, dtype: int64

In [50]:
#49. Create a second DataFrame and concatenate it with the first one.
df2 = pd.DataFrame({'Name': ['Eve'], 'Age': [24], 'Score': [88], 'Passed': [True]})
df = pd.concat([df, df2], ignore_index=True)
df.drop(5)
df

    Name  Age  Score  Passed
0    Ash   21     85    True
1   John   22     38   False
2   Alex   20     92    True
3  Perry   23     70    True
4   Lily   21     45    True
5    Eve   24     88    True

In [51]:
#50. Create two DataFrames with a common column and merge them.
df3 = pd.DataFrame({'Name': ['Ash', 'John'], 'City': ['New York', 'London']})
df_merged = pd.merge(df, df3, on='Name', how='left')
df_merged

    Name  Age  Score  Passed      City
0    Ash   21     85    True  New York
1   John   22     38   False    London
2   Alex   20     92    True       NaN
3  Perry   23     70    True       NaN
4   Lily   21     45    True       NaN
5    Eve   24     88    True       NaN