## loc and iloc

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Data

data = {
    "Player":["Virat","Rohit","MS Dhoni"],
    "Match 1": [44,55,30],
    "Match 2": [67,72,40],
    "Match 3": [82,60,50]
}

df = pd.DataFrame(data).set_index("Player")
# print("DataFrame:\n",df)
df

          Match 1  Match 2  Match 3
Player
Virat          44       67       82
Rohit          55       72       60
MS Dhoni       30       40       50

In [3]:
# First Row

print("\nFirst row:")
print("loc:",df.loc["Virat"].values)
print("iloc:",df.iloc[0].values)

First row:
loc: [44 67 82]
iloc: [44 67 82]

In [4]:
# Second Row

print("\nSecond row:")
print("loc:",df.loc["Rohit"].values)
print("iloc:",df.iloc[1].values)

Second row:
loc: [55 72 60]
iloc: [55 72 60]

In [5]:
# Specific Cell

print("\nSpecific Cell (Virat,Match 2):")
print("loc:",df.loc["Virat","Match 2"])
print("iloc:",df.iloc[0,1])

Specific Cell (Virat,Match 2):
loc: 67
iloc: 67

In [6]:
# Multiple rows
print("\nMultiple rows:")
print("loc:\n",df.loc[["Virat","Rohit"]])
print("iloc:\n",df.iloc[0:2])

Multiple rows:
loc:
         Match 1  Match 2  Match 3
Player
Virat        44       67       82
Rohit        55       72       60
iloc:
         Match 1  Match 2  Match 3
Player
Virat        44       67       82
Rohit        55       72       60

In [7]:
# Subset

print("\nSubset:")
print("loc:\n",df.loc[["Virat","MS Dhoni"],["Match 1", "Match 3"]])
print("iloc:\n",df.iloc[[0,2],[0,2]])

Subset:
loc:
           Match 1  Match 3
Player
Virat          44       82
MS Dhoni       30       50
iloc:
           Match 1  Match 3
Player
Virat          44       82
MS Dhoni       30       50

In [8]:
# Slicing 

print("\nSlicing :")
print("loc:\n",df.loc["Virat":"Rohit"])
print("iloc:\n",df.iloc[0:2])

Slicing :
loc:
         Match 1  Match 2  Match 3
Player
Virat        44       67       82
Rohit        55       72       60
iloc:
         Match 1  Match 2  Match 3
Player
Virat        44       67       82
Rohit        55       72       60

## Advanced Operations

In [9]:
# Sample Data

df = pd.DataFrame({

    "Employee" : ["Amit","Neha","Raj","Neha","Amit"],
    "Department": ["IT","HR","IT","HR","Finance"],
    "Salary": [50000,60000,np.nan,65000,70000]
})
df

  Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      NaN
3     Neha         HR  65000.0
4     Amit    Finance  70000.0

In [10]:
# Indexing

df_indexed=df.set_index("Employee")
df_indexed

         Department   Salary
Employee
Amit             IT  50000.0
Neha             HR  60000.0
Raj              IT      NaN
Neha             HR  65000.0
Amit        Finance  70000.0

In [11]:
# Filtering

df[df["Salary"]> 60000]

  Employee Department   Salary
3     Neha         HR  65000.0
4     Amit    Finance  70000.0

In [12]:
# Check Missing

df.isnull()

   Employee  Department  Salary
0     False       False   False
1     False       False   False
2     False       False    True
3     False       False   False
4     False       False   False

In [13]:
# Fill Missing
df.fillna(3)

  Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      3.0
3     Neha         HR  65000.0
4     Amit    Finance  70000.0

In [14]:
# Drop Missing
df.dropna()

  Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
3     Neha         HR  65000.0
4     Amit    Finance  70000.0

In [15]:
# Grouping
print("\nAverage Salary by Department:\n")
df.groupby("Department")["Salary"].mean()

Average Salary by Department:

Department
Finance    70000.0
HR         62500.0
IT         50000.0
Name: Salary, dtype: float64

In [16]:
# Merge (Join)

df_bonus = pd.DataFrame({
    "Employee": ["Amit","Neha","Raj"],
    "Bonus":[5000,7000,4000]
})
merged = pd.merge(df,df_bonus,on="Employee")
print("\nMerged DataFrame:\n",merged)
merged

Merged DataFrame:
   Employee Department   Salary  Bonus
0     Amit         IT  50000.0   5000
1     Neha         HR  60000.0   7000
2      Raj         IT      NaN   4000
3     Neha         HR  65000.0   7000
4     Amit    Finance  70000.0   5000

  Employee Department   Salary  Bonus
0     Amit         IT  50000.0   5000
1     Neha         HR  60000.0   7000
2      Raj         IT      NaN   4000
3     Neha         HR  65000.0   7000
4     Amit    Finance  70000.0   5000

In [17]:
# Merge (Join)
#drops the row who's value is not given or adds only common rows
df_bonus = pd.DataFrame({
    "Employee": ["Amit","Neha"],
    "Bonus":[5000,7000]
})
merged = pd.merge(df,df_bonus,on="Employee")
print("\nMerged DataFrame:\n",merged)
merged

Merged DataFrame:
   Employee Department   Salary  Bonus
0     Amit         IT  50000.0   5000
1     Neha         HR  60000.0   7000
2     Neha         HR  65000.0   7000
3     Amit    Finance  70000.0   5000

  Employee Department   Salary  Bonus
0     Amit         IT  50000.0   5000
1     Neha         HR  60000.0   7000
2     Neha         HR  65000.0   7000
3     Amit    Finance  70000.0   5000

In [18]:
# Concat 
df_new = pd.DataFrame({
    "Employee" :["Kiran"],
    "Department":["IT"],
    "Salary":[55000]
})
concat_df = pd.concat([df,df_new],ignore_index=True)
print("\nConcatenated DataFrame :\n", concat_df)
concat_df

Concatenated DataFrame :
   Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      NaN
3     Neha         HR  65000.0
4     Amit    Finance  70000.0
5    Kiran         IT  55000.0

  Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      NaN
3     Neha         HR  65000.0
4     Amit    Finance  70000.0
5    Kiran         IT  55000.0

In [19]:
# Concat 
# assigns null value for the row where value is not given
df_new = pd.DataFrame({
    "Employee" :["Kiran"],
    "Department":["IT"]
   
})
concat_df = pd.concat([df,df_new],ignore_index=True)
print("\nConcatenated DataFrame :\n", concat_df)
concat_df

Concatenated DataFrame :
   Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      NaN
3     Neha         HR  65000.0
4     Amit    Finance  70000.0
5    Kiran         IT      NaN

  Employee Department   Salary
0     Amit         IT  50000.0
1     Neha         HR  60000.0
2      Raj         IT      NaN
3     Neha         HR  65000.0
4     Amit    Finance  70000.0
5    Kiran         IT      NaN